import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

import '../firebase_options.dart';

/// Initializes Firebase using the platform-specific options generated by
/// `flutterfire configure`. Returns `true` on success.
///
/// On Linux (or any platform `DefaultFirebaseOptions` doesn't cover), the
/// init throws; we catch it so the app falls back to the local repository.
Future<bool> tryInitFirebase() async {
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    return true;
  } catch (e, st) {
    if (kDebugMode) {
      debugPrint('Firebase not initialized (using local storage): $e');
      debugPrintStack(stackTrace: st);
    }
    return false;
  }
}
