import 'package:flutter/services.dart' show rootBundle;
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../core/formatters.dart';
import '../models/bill.dart';
import '../models/reading.dart';
import '../models/room.dart';
import '../models/settings.dart';
import 'bill_calculator.dart';

class _L {
  final String invoice;
  final String room;
  final String billingPeriod;
  final String from;
  final String to;
  final String days;
  final String electricity;
  final String water;
  final String prevMeter;
  final String currMeter;
  final String usage;
  final String unitPrice;
  final String amount;
  final String total;
  final String generatedBy;
  final String incomplete;
  final String complete;
  final String description;
  final String qty;

  const _L({
    required this.invoice,
    required this.room,
    required this.billingPeriod,
    required this.from,
    required this.to,
    required this.days,
    required this.electricity,
    required this.water,
    required this.prevMeter,
    required this.currMeter,
    required this.usage,
    required this.unitPrice,
    required this.amount,
    required this.total,
    required this.generatedBy,
    required this.incomplete,
    required this.complete,
    required this.description,
    required this.qty,
  });

  factory _L.of(String locale) {
    if (locale == 'km') {
      return const _L(
        invoice: 'វិក្កយបត្រ',
        room: 'បន្ទប់',
        billingPeriod: 'រយៈពេលគិតថ្លៃ',
        from: 'ចាប់ពី',
        to: 'ដល់',
        days: 'ថ្ងៃ',
        electricity: 'អគ្គិសនី',
        water: 'ទឹក',
        prevMeter: 'ម៉ែត្រមុន',
        currMeter: 'ម៉ែត្រថ្មី',
        usage: 'ប្រើប្រាស់',
        unitPrice: 'តម្លៃ/ឯកតា',
        amount: 'ចំនួនទឹកប្រាក់',
        total: 'សរុប',
        generatedBy: 'បង្កើតដោយ My Bill',
        incomplete: 'មិនទាន់គ្រប់មួយខែ',
        complete: 'គ្រប់មួយខែ',
        description: 'បរិយាយ',
        qty: 'បរិមាណ',
      );
    }
    return const _L(
      invoice: 'INVOICE',
      room: 'Room',
      billingPeriod: 'Billing Period',
      from: 'From',
      to: 'To',
      days: 'days',
      electricity: 'Electricity',
      water: 'Water',
      prevMeter: 'Prev',
      currMeter: 'Curr',
      usage: 'Usage',
      unitPrice: 'Unit Price',
      amount: 'Amount',
      total: 'Total',
      generatedBy: 'Generated by My Bill',
      incomplete: 'Incomplete',
      complete: 'Complete',
      description: 'Description',
      qty: 'Qty',
    );
  }
}

class PdfService {
  PdfService._();
  static final PdfService instance = PdfService._();

  pw.Font? _khmerFont;

  Future<pw.Font> _loadKhmerFont() async {
    if (_khmerFont != null) return _khmerFont!;
    final bytes = await rootBundle.load(
      'assets/fonts/NotoSansKhmer-Regular.ttf',
    );
    _khmerFont = pw.Font.ttf(bytes);
    return _khmerFont!;
  }

  Future<pw.ThemeData> _theme() async {
    final font = await _loadKhmerFont();
    return pw.ThemeData.withFont(base: font, bold: font);
  }

  Future<pw.Document> buildInvoice({
    required Room room,
    required Reading reading,
    required AppSettings settings,
    required String localeCode,
  }) async {
    final theme = await _theme();
    final doc = pw.Document(theme: theme);
    final b = computeBill(reading, settings);
    doc.addPage(_page(room, reading, settings, b, localeCode));
    return doc;
  }

  Future<pw.Document> buildInvoiceBatch({
    required Map<String, Room> roomsById,
    required List<Reading> readings,
    required AppSettings settings,
    required String localeCode,
  }) async {
    final theme = await _theme();
    final doc = pw.Document(theme: theme);
    for (final r in readings) {
      final room = roomsById[r.roomId] ?? Room(id: r.roomId, name: r.roomId);
      final b = computeBill(r, settings);
      doc.addPage(_page(room, r, settings, b, localeCode));
    }
    return doc;
  }

  pw.Page _page(
    Room room,
    Reading r,
    AppSettings s,
    BillBreakdown b,
    String locale,
  ) {
    final l = _L.of(locale);
    final dateFmt = DateFormat('dd/MM/yyyy', locale);
    final prevDate = r.prevElecDate;
    final currDate = r.currElecDate;
    final hasDates = prevDate != null && currDate != null;
    final daysSpan = hasDates ? currDate.difference(prevDate).inDays : null;
    final khrPerUsd = s.khrPerUsd;

    return pw.Page(
      pageFormat: PdfPageFormat.a5,
      margin: const pw.EdgeInsets.symmetric(horizontal: 32, vertical: 28),
      build: (ctx) => pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.stretch,
        children: [
          // ─── HEADER ───
          pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Expanded(
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      l.invoice,
                      style: pw.TextStyle(
                        fontSize: 28,
                        fontWeight: pw.FontWeight.bold,
                        color: PdfColors.blueGrey800,
                      ),
                    ),
                    pw.SizedBox(height: 6),
                    pw.Text(
                      formatYearMonthHuman(r.month, locale),
                      style: const pw.TextStyle(
                        fontSize: 12,
                        color: PdfColors.blueGrey600,
                      ),
                    ),
                  ],
                ),
              ),
              pw.Container(
                padding: const pw.EdgeInsets.symmetric(horizontal: 16, vertical: 10),
                decoration: pw.BoxDecoration(
                  color: PdfColors.blueGrey800,
                  borderRadius: pw.BorderRadius.circular(8),
                ),
                child: pw.Text(
                  room.name,
                  style: pw.TextStyle(
                    fontSize: 14,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.white,
                  ),
                ),
              ),
            ],
          ),
          pw.SizedBox(height: 20),

          // ─── BILLING PERIOD ───
          pw.Container(
            padding: const pw.EdgeInsets.symmetric(horizontal: 14, vertical: 12),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey100,
              borderRadius: pw.BorderRadius.circular(6),
            ),
            child: pw.Row(
              children: [
                pw.Expanded(
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(
                        l.billingPeriod,
                        style: pw.TextStyle(
                          fontSize: 8,
                          fontWeight: pw.FontWeight.bold,
                          color: PdfColors.blueGrey600,
                          letterSpacing: 0.5,
                        ),
                      ),
                      pw.SizedBox(height: 6),
                      if (hasDates)
                        pw.Text(
                          '${dateFmt.format(prevDate)}  —  ${dateFmt.format(currDate)}',
                          style: pw.TextStyle(
                            fontSize: 11,
                            fontWeight: pw.FontWeight.bold,
                            color: PdfColors.blueGrey900,
                          ),
                        )
                      else
                        pw.Text(
                          formatYearMonthHuman(r.month, locale),
                          style: const pw.TextStyle(fontSize: 11),
                        ),
                    ],
                  ),
                ),
                if (daysSpan != null) ...[
                  pw.Container(
                    padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 6),
                    decoration: pw.BoxDecoration(
                      color: r.isMonthComplete
                          ? const PdfColor.fromInt(0xFFD1FAE5)
                          : const PdfColor.fromInt(0xFFFEF3C7),
                      borderRadius: pw.BorderRadius.circular(12),
                    ),
                    child: pw.Text(
                      '$daysSpan ${l.days} • ${r.isMonthComplete ? l.complete : l.incomplete}',
                      style: pw.TextStyle(
                        fontSize: 8,
                        fontWeight: pw.FontWeight.bold,
                        color: r.isMonthComplete
                            ? const PdfColor.fromInt(0xFF065F46)
                            : const PdfColor.fromInt(0xFF92400E),
                      ),
                    ),
                  ),
                ],
              ],
            ),
          ),
          pw.SizedBox(height: 18),

          // ─── TABLE ───
          pw.Table(
            border: pw.TableBorder(
              horizontalInside: const pw.BorderSide(color: PdfColors.grey300, width: 0.5),
              bottom: const pw.BorderSide(color: PdfColors.grey300, width: 0.5),
              top: const pw.BorderSide(color: PdfColors.blueGrey800, width: 1.5),
            ),
            columnWidths: const {
              0: pw.FlexColumnWidth(3.2),
              1: pw.FlexColumnWidth(2),
              2: pw.FlexColumnWidth(2),
              3: pw.FlexColumnWidth(2.4),
            },
            children: [
              // Header row
              pw.TableRow(
                children: [
                  _hCell(l.description),
                  _hCell(l.qty, align: pw.TextAlign.center),
                  _hCell(l.unitPrice, align: pw.TextAlign.right),
                  _hCell(l.amount, align: pw.TextAlign.right),
                ],
              ),
              // Electricity row
              pw.TableRow(
                children: [
                  _bodyCell(
                    l.electricity,
                    sub: '${l.prevMeter}: ${_num(r.prevElec)}  -  ${l.currMeter}: ${_num(r.currElec)}',
                  ),
                  _textCell('${_num(b.elecUsageKwh)} kWh', align: pw.TextAlign.center),
                  _textCell('${formatInt(s.elecRateKhrPerKwh)} KHR', align: pw.TextAlign.right),
                  _textCell(_fmtKhr(b.elecAmountKhr), align: pw.TextAlign.right, bold: true),
                ],
              ),
              // Water row
              pw.TableRow(
                children: [
                  _bodyCell(
                    l.water,
                    sub: '${l.prevMeter}: ${_num(r.prevWater)}  -  ${l.currMeter}: ${_num(r.currWater)}',
                  ),
                  _textCell('${_num(b.waterUsageM3)} m3', align: pw.TextAlign.center),
                  _textCell('${formatInt(s.waterRateKhrPerM3)} KHR', align: pw.TextAlign.right),
                  _textCell(_fmtKhr(b.waterAmountKhr), align: pw.TextAlign.right, bold: true),
                ],
              ),
            ],
          ),
          pw.SizedBox(height: 14),

          // ─── TOTAL BOX ───
          pw.Container(
            padding: const pw.EdgeInsets.all(14),
            decoration: pw.BoxDecoration(
              color: PdfColors.blueGrey800,
              borderRadius: pw.BorderRadius.circular(8),
            ),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(
                  l.total,
                  style: pw.TextStyle(
                    fontSize: 14,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.white,
                  ),
                ),
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.end,
                  children: [
                    pw.Text(
                      _fmtKhr(b.totalKhr),
                      style: pw.TextStyle(
                        fontSize: 18,
                        fontWeight: pw.FontWeight.bold,
                        color: PdfColors.white,
                      ),
                    ),
                    pw.SizedBox(height: 2),
                    pw.Text(
                      _fmtUsd(khrPerUsd == 0 ? 0 : b.totalKhr / khrPerUsd),
                      style: const pw.TextStyle(
                        fontSize: 10,
                        color: PdfColors.grey400,
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),

          pw.Spacer(),

          // ─── FOOTER ───
          pw.Divider(color: PdfColors.grey300, height: 20),
          pw.Center(
            child: pw.Text(
              l.generatedBy,
              style: const pw.TextStyle(
                fontSize: 8,
                color: PdfColors.grey500,
              ),
            ),
          ),
        ],
      ),
    );
  }

  // ─── Table cell helpers ───

  pw.Widget _hCell(String text, {pw.TextAlign align = pw.TextAlign.left}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 8),
      child: pw.Text(
        text,
        textAlign: align,
        style: pw.TextStyle(
          fontSize: 8,
          fontWeight: pw.FontWeight.bold,
          color: PdfColors.blueGrey600,
        ),
      ),
    );
  }

  pw.Widget _bodyCell(String title, {String? sub}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 10),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            title,
            style: pw.TextStyle(
              fontSize: 10,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.blueGrey900,
            ),
          ),
          if (sub != null) ...[
            pw.SizedBox(height: 2),
            pw.Text(
              sub,
              style: const pw.TextStyle(fontSize: 7, color: PdfColors.blueGrey500),
            ),
          ],
        ],
      ),
    );
  }

  pw.Widget _textCell(
    String text, {
    pw.TextAlign align = pw.TextAlign.left,
    bool bold = false,
  }) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 12),
      child: pw.Text(
        text,
        textAlign: align,
        style: pw.TextStyle(
          fontSize: 9,
          fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal,
          color: PdfColors.blueGrey900,
        ),
      ),
    );
  }

  String _num(double v) =>
      v == v.roundToDouble() ? formatInt(v) : v.toStringAsFixed(1);

  String _fmtKhr(num value) => '${formatInt(value.round())} KHR';

  String _fmtUsd(num value) => '\$${value.toStringAsFixed(2)}';

  Future<void> printDoc(pw.Document doc, {String? name}) async {
    await Printing.layoutPdf(
      onLayout: (format) => doc.save(),
      name: name ?? 'invoice',
    );
  }

  Future<void> shareDoc(pw.Document doc, {required String fileName}) async {
    final bytes = await doc.save();
    await Printing.sharePdf(bytes: bytes, filename: fileName);
  }
}
