import 'dart:typed_data';

import 'package:flutter/services.dart' show rootBundle;
import 'package:image/image.dart' as img;
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../core/formatters.dart';
import '../models/bill.dart';
import '../models/reading.dart';
import '../models/room.dart';
import '../models/settings.dart';
import 'bill_calculator.dart';

class _L {
  final String invoice;
  final String room;
  final String billingPeriod;
  final String from;
  final String to;
  final String days;
  final String electricity;
  final String water;
  final String roomPrice;
  final String prevMeter;
  final String currMeter;
  final String usage;
  final String unitPrice;
  final String amount;
  final String total;
  final String generatedBy;
  final String incomplete;
  final String complete;
  final String description;
  final String qty;
  final String scanToPay;
  final String amountDue;

  const _L({
    required this.invoice,
    required this.room,
    required this.billingPeriod,
    required this.from,
    required this.to,
    required this.days,
    required this.electricity,
    required this.water,
    required this.roomPrice,
    required this.prevMeter,
    required this.currMeter,
    required this.usage,
    required this.unitPrice,
    required this.amount,
    required this.total,
    required this.generatedBy,
    required this.incomplete,
    required this.complete,
    required this.description,
    required this.qty,
    required this.scanToPay,
    required this.amountDue,
  });

  factory _L.of(String locale) {
    if (locale == 'km') {
      return const _L(
        invoice: 'វិក្កយបត្រ',
        room: 'បន្ទប់',
        billingPeriod: 'រយៈពេលគិតថ្លៃ',
        from: 'ចាប់ពី',
        to: 'ដល់',
        days: 'ថ្ងៃ',
        electricity: 'អគ្គិសនី',
        water: 'ទឹក',
        roomPrice: 'តម្លៃបន្ទប់',
        prevMeter: 'ម៉ែត្រមុន',
        currMeter: 'ម៉ែត្រថ្មី',
        usage: 'ប្រើប្រាស់',
        unitPrice: 'តម្លៃ/ឯកតា',
        amount: 'ចំនួនទឹកប្រាក់',
        total: 'សរុប',
        generatedBy: 'បង្កើតដោយ My Bill',
        incomplete: 'មិនទាន់គ្រប់មួយខែ',
        complete: 'គ្រប់មួយខែ',
        description: 'បរិយាយ',
        qty: 'បរិមាណ',
        scanToPay: 'ស្កេនដើម្បីបង់ប្រាក់ (KHQR)',
        amountDue: 'ចំនួនត្រូវបង់',
      );
    }
    return const _L(
      invoice: 'INVOICE',
      room: 'Room',
      billingPeriod: 'Billing Period',
      from: 'From',
      to: 'To',
      days: 'days',
      electricity: 'Electricity',
      water: 'Water',
      roomPrice: 'Room Price',
      prevMeter: 'Prev',
      currMeter: 'Curr',
      usage: 'Usage',
      unitPrice: 'Unit Price',
      amount: 'Amount',
      total: 'Total',
      generatedBy: 'Generated by My Bill',
      incomplete: 'Incomplete',
      complete: 'Complete',
      description: 'Description',
      qty: 'Qty',
      scanToPay: 'Scan to pay (KHQR)',
      amountDue: 'Amount Due',
    );
  }
}

class PdfService {
  PdfService._();
  static final PdfService instance = PdfService._();

  /// Print resolution for the embedded payment QR (KHQR card).
  static const double _paymentQrDpi = 300;

  /// Keeps the QR large enough to scan without dominating the invoice.
  static const double _paymentQrMaxWidth = 250;
  static const double _paymentQrMaxHeight = 215;

  pw.Font? _khmerFont;
  pw.MemoryImage? _paymentQrImage;

  Future<pw.Font> _loadKhmerFont() async {
    if (_khmerFont != null) return _khmerFont!;
    final bytes = await rootBundle.load(
      'assets/fonts/NotoSansKhmer-Regular.ttf',
    );
    _khmerFont = pw.Font.ttf(bytes);
    return _khmerFont!;
  }

  Future<pw.ThemeData> _theme() async {
    final font = await _loadKhmerFont();
    return pw.ThemeData.withFont(base: font, bold: font);
  }

  Future<pw.MemoryImage> _loadPaymentQrImage() async {
    if (_paymentQrImage != null) return _paymentQrImage!;
    final bytes = await rootBundle.load('assets/images/payment_qr.png');
    final raw = bytes.buffer.asUint8List();
    _paymentQrImage = pw.MemoryImage(_cropPaymentQr(raw));
    return _paymentQrImage!;
  }

  /// Crops the ABA KHQR poster to the scannable card (banner + QR), dropping the
  /// poster header, account numbers, and footer so the code can fill the PDF.
  Uint8List _cropPaymentQr(Uint8List bytes) {
    final decoded = img.decodeImage(bytes);
    if (decoded == null) return bytes;

    final cropped = img.copyCrop(
      decoded,
      x: 118,
      y: 300,
      width: 488,
      height: 430,
    );
    return Uint8List.fromList(img.encodeJpg(cropped, quality: 95));
  }

  Future<pw.Document> buildInvoice({
    required Room room,
    required Reading reading,
    required AppSettings settings,
    required String localeCode,
  }) async {
    final theme = await _theme();
    final qrImage = await _loadPaymentQrImage();
    final doc = pw.Document(theme: theme);
    final b = computeBill(reading, settings);
    doc.addPage(_page(room, reading, settings, b, localeCode, qrImage));
    return doc;
  }

  Future<pw.Document> buildInvoiceBatch({
    required Map<String, Room> roomsById,
    required List<Reading> readings,
    required AppSettings settings,
    required String localeCode,
  }) async {
    final theme = await _theme();
    final qrImage = await _loadPaymentQrImage();
    final doc = pw.Document(theme: theme);
    for (final r in readings) {
      final room = roomsById[r.roomId] ?? Room(id: r.roomId, name: r.roomId);
      final b = computeBill(r, settings);
      doc.addPage(_page(room, r, settings, b, localeCode, qrImage));
    }
    return doc;
  }

  pw.Page _page(
    Room room,
    Reading r,
    AppSettings s,
    BillBreakdown b,
    String locale,
    pw.MemoryImage qrImage,
  ) {
    final l = _L.of(locale);
    final dateFmt = DateFormat('dd/MM/yyyy', locale);
    final prevDate = r.prevElecDate;
    final currDate = r.currElecDate;
    final hasDates = prevDate != null && currDate != null;
    final daysSpan = hasDates ? currDate.difference(prevDate).inDays : null;
    final khrPerUsd = s.khrPerUsd;
    final roomPriceUsd = room.priceUsd;
    final roomPriceKhr = roomPriceUsd * khrPerUsd;
    // Tariffs are priced in USD; the KHR figures are derived via the exchange
    // rate so the invoice total is calculated in dollars first.
    final utilitiesUsd = b.totalUsd;
    final grandTotalUsd = utilitiesUsd + roomPriceUsd;
    final grandTotalKhr = grandTotalUsd * khrPerUsd;

    return pw.Page(
      pageFormat: PdfPageFormat.a5,
      margin: const pw.EdgeInsets.symmetric(horizontal: 18, vertical: 12),
      build: (ctx) => pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.stretch,
        children: [
          // ─── HEADER ───
          pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Expanded(
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      l.invoice,
                      style: pw.TextStyle(
                        fontSize: 18,
                        fontWeight: pw.FontWeight.bold,
                        color: PdfColors.blueGrey800,
                      ),
                    ),
                    pw.Text(
                      formatYearMonthHuman(r.month, locale),
                      style: const pw.TextStyle(
                        fontSize: 10,
                        color: PdfColors.blueGrey600,
                      ),
                    ),
                  ],
                ),
              ),
              pw.Container(
                padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 6),
                decoration: pw.BoxDecoration(
                  color: PdfColors.blueGrey800,
                  borderRadius: pw.BorderRadius.circular(6),
                ),
                child: pw.Text(
                  room.name,
                  style: pw.TextStyle(
                    fontSize: 11,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.white,
                  ),
                ),
              ),
            ],
          ),
          pw.SizedBox(height: 6),

          // ─── BILLING PERIOD ───
          pw.Container(
            padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 6),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey100,
              borderRadius: pw.BorderRadius.circular(6),
            ),
            child: pw.Row(
              children: [
                pw.Expanded(
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(
                        l.billingPeriod,
                        style: pw.TextStyle(
                          fontSize: 7,
                          fontWeight: pw.FontWeight.bold,
                          color: PdfColors.blueGrey600,
                          letterSpacing: 0.5,
                        ),
                      ),
                      pw.SizedBox(height: 2),
                      if (hasDates)
                        pw.Text(
                          '${dateFmt.format(prevDate)}  —  ${dateFmt.format(currDate)}',
                          style: pw.TextStyle(
                            fontSize: 9,
                            fontWeight: pw.FontWeight.bold,
                            color: PdfColors.blueGrey900,
                          ),
                        )
                      else
                        pw.Text(
                          formatYearMonthHuman(r.month, locale),
                          style: const pw.TextStyle(fontSize: 9),
                        ),
                    ],
                  ),
                ),
                if (daysSpan != null) ...[
                  pw.Container(
                    padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                    decoration: pw.BoxDecoration(
                      color: r.isMonthComplete
                          ? const PdfColor.fromInt(0xFFD1FAE5)
                          : const PdfColor.fromInt(0xFFFEF3C7),
                      borderRadius: pw.BorderRadius.circular(10),
                    ),
                    child: pw.Text(
                      '$daysSpan ${l.days} • ${r.isMonthComplete ? l.complete : l.incomplete}',
                      style: pw.TextStyle(
                        fontSize: 7,
                        fontWeight: pw.FontWeight.bold,
                        color: r.isMonthComplete
                            ? const PdfColor.fromInt(0xFF065F46)
                            : const PdfColor.fromInt(0xFF92400E),
                      ),
                    ),
                  ),
                ],
              ],
            ),
          ),
          pw.SizedBox(height: 6),

          // ─── TABLE ───
          pw.Table(
            border: pw.TableBorder(
              horizontalInside: const pw.BorderSide(color: PdfColors.grey300, width: 0.5),
              bottom: const pw.BorderSide(color: PdfColors.grey300, width: 0.5),
              top: const pw.BorderSide(color: PdfColors.blueGrey800, width: 1.5),
            ),
            columnWidths: const {
              0: pw.FlexColumnWidth(3.2),
              1: pw.FlexColumnWidth(2),
              2: pw.FlexColumnWidth(2),
              3: pw.FlexColumnWidth(2.4),
            },
            children: [
              // Header row
              pw.TableRow(
                children: [
                  _hCell(l.description),
                  _hCell(l.qty, align: pw.TextAlign.center),
                  _hCell(l.unitPrice, align: pw.TextAlign.right),
                  _hCell(l.amount, align: pw.TextAlign.right),
                ],
              ),
              // Electricity row
              pw.TableRow(
                children: [
                  _bodyCell(
                    l.electricity,
                    sub: '${l.prevMeter}: ${_num(r.prevElec)}  -  ${l.currMeter}: ${_num(r.currElec)}',
                  ),
                  _textCell('${_num(b.elecUsageKwh)} kWh', align: pw.TextAlign.center),
                  _textCell(_fmtUsd(s.elecRateUsdPerKwh), align: pw.TextAlign.right),
                  _amountCell(b.elecAmountUsd, b.elecAmountKhr),
                ],
              ),
              // Water row
              pw.TableRow(
                children: [
                  _bodyCell(
                    l.water,
                    sub: '${l.prevMeter}: ${_num(r.prevWater)}  -  ${l.currMeter}: ${_num(r.currWater)}',
                  ),
                  _textCell('${_num(b.waterUsageM3)} m3', align: pw.TextAlign.center),
                  _textCell(_fmtUsd(s.waterRateUsdPerM3), align: pw.TextAlign.right),
                  _amountCell(b.waterAmountUsd, b.waterAmountKhr),
                ],
              ),
              // Room price row
              if (roomPriceUsd > 0)
                pw.TableRow(
                  children: [
                    _bodyCell(l.roomPrice),
                    _textCell('1', align: pw.TextAlign.center),
                    _textCell(_fmtUsd(roomPriceUsd), align: pw.TextAlign.right),
                    _amountCell(roomPriceUsd, roomPriceKhr),
                  ],
                ),
            ],
          ),
          pw.SizedBox(height: 10),

          // ─── SUBTOTAL SUMMARY ───
          // Shows the calculation clearly: utilities summed in KHR, converted
          // to dollars, then combined with the room price (already in USD).
          pw.Container(
            padding: const pw.EdgeInsets.symmetric(horizontal: 14, vertical: 4),
            child: pw.Column(
              children: [
                _summaryRow(
                  '${l.electricity} + ${l.water}',
                  '${_fmtKhr(b.totalKhr)}  =  ${_fmtUsd(utilitiesUsd)}',
                ),
                if (roomPriceUsd > 0) ...[
                  pw.SizedBox(height: 4),
                  _summaryRow(l.roomPrice, _fmtUsd(roomPriceUsd)),
                ],
              ],
            ),
          ),
          pw.SizedBox(height: 8),

          // ─── TOTAL BOX ───
          pw.Container(
            padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 8),
            decoration: pw.BoxDecoration(
              color: PdfColors.blueGrey800,
              borderRadius: pw.BorderRadius.circular(6),
            ),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(
                  l.total,
                  style: pw.TextStyle(
                    fontSize: 12,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.white,
                  ),
                ),
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.end,
                  children: [
                    pw.Text(
                      _fmtUsd(grandTotalUsd),
                      style: pw.TextStyle(
                        fontSize: 12,
                        fontWeight: pw.FontWeight.bold,
                        color: PdfColors.white,
                      ),
                    ),
                    pw.Text(
                      _fmtKhr(grandTotalKhr),
                      style: const pw.TextStyle(
                        fontSize: 10,
                        color: PdfColors.grey400,
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
          pw.SizedBox(height: 6),

          // ─── PAYMENT QR ───
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.stretch,
              children: [
                pw.Text(
                  l.scanToPay,
                  textAlign: pw.TextAlign.center,
                  style: pw.TextStyle(
                    fontSize: 9,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.blueGrey700,
                  ),
                ),
                pw.SizedBox(height: 6),
                pw.Expanded(
                  child: pw.Center(
                    child: pw.Container(
                      constraints: const pw.BoxConstraints(
                        maxWidth: _paymentQrMaxWidth,
                        maxHeight: _paymentQrMaxHeight,
                      ),
                      padding: const pw.EdgeInsets.all(6),
                      decoration: pw.BoxDecoration(
                        color: PdfColors.white,
                        borderRadius: pw.BorderRadius.circular(8),
                        border: pw.Border.all(
                          color: PdfColors.grey300,
                          width: 0.5,
                        ),
                      ),
                      child: pw.Image(
                        qrImage,
                        fit: pw.BoxFit.contain,
                        dpi: _paymentQrDpi,
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  // ─── Table cell helpers ───

  pw.Widget _hCell(String text, {pw.TextAlign align = pw.TextAlign.left}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 6),
      child: pw.Text(
        text,
        textAlign: align,
        style: pw.TextStyle(
          fontSize: 8,
          fontWeight: pw.FontWeight.bold,
          color: PdfColors.blueGrey600,
        ),
      ),
    );
  }

  pw.Widget _bodyCell(String title, {String? sub}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 8),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            title,
            style: pw.TextStyle(
              fontSize: 10,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.blueGrey900,
            ),
          ),
          if (sub != null) ...[
            pw.SizedBox(height: 2),
            pw.Text(
              sub,
              style: const pw.TextStyle(fontSize: 7, color: PdfColors.blueGrey500),
            ),
          ],
        ],
      ),
    );
  }

  pw.Widget _textCell(
    String text, {
    pw.TextAlign align = pw.TextAlign.left,
    bool bold = false,
  }) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 9),
      child: pw.Text(
        text,
        textAlign: align,
        style: pw.TextStyle(
          fontSize: 9,
          fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal,
          color: PdfColors.blueGrey900,
        ),
      ),
    );
  }

  pw.Widget _amountCell(num usd, num khr) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 9),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.end,
        children: [
          pw.Text(
            _fmtUsd(usd),
            textAlign: pw.TextAlign.right,
            style: pw.TextStyle(
              fontSize: 9,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.blueGrey900,
            ),
          ),
          pw.SizedBox(height: 1),
          pw.Text(
            _fmtKhr(khr),
            textAlign: pw.TextAlign.right,
            style: const pw.TextStyle(
              fontSize: 8,
              color: PdfColors.blueGrey500,
            ),
          ),
        ],
      ),
    );
  }

  pw.Widget _summaryRow(String label, String value) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Text(
          label,
          style: const pw.TextStyle(
            fontSize: 9,
            color: PdfColors.blueGrey600,
          ),
        ),
        pw.Text(
          value,
          style: pw.TextStyle(
            fontSize: 9,
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.blueGrey900,
          ),
        ),
      ],
    );
  }

  String _num(double v) =>
      v == v.roundToDouble() ? formatInt(v) : v.toStringAsFixed(1);

  String _fmtKhr(num value) => '${formatInt(value.round())} KHR';

  String _fmtUsd(num value) => '\$${value.toStringAsFixed(2)}';

  Future<void> printDoc(pw.Document doc, {String? name}) async {
    await Printing.layoutPdf(
      onLayout: (format) => doc.save(),
      name: name ?? 'invoice',
    );
  }

  Future<void> shareDoc(pw.Document doc, {required String fileName}) async {
    final bytes = await doc.save();
    await Printing.sharePdf(bytes: bytes, filename: fileName);
  }
}
