import 'package:flutter/services.dart' show rootBundle;
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../core/formatters.dart';
import '../models/bill.dart';
import '../models/reading.dart';
import '../models/room.dart';
import '../models/settings.dart';
import 'bill_calculator.dart';

class _InvoiceLabels {
  final String invoice;
  final String room;
  final String billingPeriod;
  final String fromDate;
  final String toDate;
  final String days;
  final String item;
  final String prevMeter;
  final String currMeter;
  final String usage;
  final String rate;
  final String amount;
  final String electricity;
  final String water;
  final String total;
  final String subtotalElec;
  final String subtotalWater;
  final String generatedBy;
  final String kwhUnit;
  final String m3Unit;
  final String perKwh;
  final String perM3;
  final String monthNotComplete;
  final String complete;

  const _InvoiceLabels({
    required this.invoice,
    required this.room,
    required this.billingPeriod,
    required this.fromDate,
    required this.toDate,
    required this.days,
    required this.item,
    required this.prevMeter,
    required this.currMeter,
    required this.usage,
    required this.rate,
    required this.amount,
    required this.electricity,
    required this.water,
    required this.total,
    required this.subtotalElec,
    required this.subtotalWater,
    required this.generatedBy,
    required this.kwhUnit,
    required this.m3Unit,
    required this.perKwh,
    required this.perM3,
    required this.monthNotComplete,
    required this.complete,
  });

  factory _InvoiceLabels.forLocale(String locale) {
    if (locale == 'km') {
      return const _InvoiceLabels(
        invoice: 'វិក្កយបត្រ',
        room: 'បន្ទប់',
        billingPeriod: 'រយៈពេលគិតថ្លៃ',
        fromDate: 'ចាប់ពី',
        toDate: 'ដល់',
        days: 'ថ្ងៃ',
        item: 'ប្រភេទ',
        prevMeter: 'ម៉ែត្រមុន',
        currMeter: 'ម៉ែត្រថ្មី',
        usage: 'ប្រើប្រាស់',
        rate: 'តម្លៃ',
        amount: 'ចំនួនទឹកប្រាក់',
        electricity: 'អគ្គិសនី',
        water: 'ទឹក',
        total: 'សរុប',
        subtotalElec: 'សរុបអគ្គិសនី',
        subtotalWater: 'សរុបទឹក',
        generatedBy: 'បង្កើតដោយ My Bill',
        kwhUnit: 'kWh',
        m3Unit: 'm³',
        perKwh: '៛/kWh',
        perM3: '៛/m³',
        monthNotComplete: 'មិនទាន់គ្រប់មួយខែ',
        complete: 'គ្រប់មួយខែ',
      );
    }
    return const _InvoiceLabels(
      invoice: 'INVOICE',
      room: 'Room',
      billingPeriod: 'Billing Period',
      fromDate: 'From',
      toDate: 'To',
      days: 'days',
      item: 'Item',
      prevMeter: 'Prev Meter',
      currMeter: 'Curr Meter',
      usage: 'Usage',
      rate: 'Rate',
      amount: 'Amount',
      electricity: 'Electricity',
      water: 'Water',
      total: 'TOTAL',
      subtotalElec: 'Electricity Subtotal',
      subtotalWater: 'Water Subtotal',
      generatedBy: 'Generated by My Bill',
      kwhUnit: 'kWh',
      m3Unit: 'm³',
      perKwh: 'KHR/kWh',
      perM3: 'KHR/m³',
      monthNotComplete: 'Incomplete month',
      complete: 'Full month',
    );
  }
}

class PdfService {
  PdfService._();
  static final PdfService instance = PdfService._();

  pw.Font? _khmerFont;

  Future<pw.Font> _loadKhmerFont() async {
    if (_khmerFont != null) return _khmerFont!;
    final bytes = await rootBundle.load(
      'assets/fonts/NotoSansKhmer-Regular.ttf',
    );
    _khmerFont = pw.Font.ttf(bytes);
    return _khmerFont!;
  }

  Future<pw.ThemeData> _theme() async {
    final font = await _loadKhmerFont();
    return pw.ThemeData.withFont(base: font, bold: font);
  }

  Future<pw.Document> buildInvoice({
    required Room room,
    required Reading reading,
    required AppSettings settings,
    required String localeCode,
  }) async {
    final theme = await _theme();
    final doc = pw.Document(theme: theme);
    final b = computeBill(reading, settings);
    doc.addPage(_buildInvoicePage(room, reading, settings, b, localeCode));
    return doc;
  }

  Future<pw.Document> buildInvoiceBatch({
    required Map<String, Room> roomsById,
    required List<Reading> readings,
    required AppSettings settings,
    required String localeCode,
  }) async {
    final theme = await _theme();
    final doc = pw.Document(theme: theme);
    for (final r in readings) {
      final room = roomsById[r.roomId] ?? Room(id: r.roomId, name: r.roomId);
      final b = computeBill(r, settings);
      doc.addPage(_buildInvoicePage(room, r, settings, b, localeCode));
    }
    return doc;
  }

  pw.Page _buildInvoicePage(
    Room room,
    Reading r,
    AppSettings s,
    BillBreakdown b,
    String localeCode,
  ) {
    final labels = _InvoiceLabels.forLocale(localeCode);
    final dateFmt = DateFormat.yMMMd(localeCode);
    final prevDate = r.prevElecDate;
    final currDate = r.currElecDate;
    final daysSpan = (prevDate != null && currDate != null)
        ? currDate.difference(prevDate).inDays
        : null;

    return pw.Page(
      pageFormat: PdfPageFormat.a5,
      margin: const pw.EdgeInsets.all(24),
      build: (ctx) => pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          // Header
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    labels.invoice,
                    style: pw.TextStyle(
                      fontSize: 22,
                      fontWeight: pw.FontWeight.bold,
                    ),
                  ),
                  pw.SizedBox(height: 2),
                  pw.Text(
                    formatYearMonthHuman(r.month, localeCode),
                    style: const pw.TextStyle(
                      fontSize: 11,
                      color: PdfColors.grey700,
                    ),
                  ),
                ],
              ),
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.end,
                children: [
                  pw.Text(
                    '${labels.room}: ${room.name}',
                    style: pw.TextStyle(
                      fontSize: 14,
                      fontWeight: pw.FontWeight.bold,
                    ),
                  ),
                ],
              ),
            ],
          ),
          pw.SizedBox(height: 14),

          // Billing period
          pw.Container(
            padding: const pw.EdgeInsets.all(10),
            decoration: pw.BoxDecoration(
              color: PdfColors.blue50,
              borderRadius: pw.BorderRadius.circular(4),
              border: pw.Border.all(color: PdfColors.blue100),
            ),
            child: pw.Row(
              children: [
                pw.Expanded(
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(
                        labels.billingPeriod,
                        style: pw.TextStyle(
                          fontSize: 9,
                          fontWeight: pw.FontWeight.bold,
                          color: PdfColors.blue800,
                        ),
                      ),
                      pw.SizedBox(height: 4),
                      if (prevDate != null && currDate != null) ...[
                        pw.Row(
                          children: [
                            pw.Text(
                              '${labels.fromDate}: ',
                              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
                            ),
                            pw.Text(
                              dateFmt.format(prevDate),
                              style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold),
                            ),
                            pw.Text(
                              '    ${labels.toDate}: ',
                              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
                            ),
                            pw.Text(
                              dateFmt.format(currDate),
                              style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold),
                            ),
                          ],
                        ),
                      ] else
                        pw.Text(
                          formatYearMonthHuman(r.month, localeCode),
                          style: const pw.TextStyle(fontSize: 10),
                        ),
                    ],
                  ),
                ),
                if (daysSpan != null)
                  pw.Container(
                    padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                    decoration: pw.BoxDecoration(
                      color: r.isMonthComplete ? PdfColors.green50 : PdfColors.orange50,
                      borderRadius: pw.BorderRadius.circular(4),
                      border: pw.Border.all(
                        color: r.isMonthComplete ? PdfColors.green200 : PdfColors.orange200,
                      ),
                    ),
                    child: pw.Column(
                      children: [
                        pw.Text(
                          '$daysSpan ${labels.days}',
                          style: pw.TextStyle(
                            fontSize: 11,
                            fontWeight: pw.FontWeight.bold,
                            color: r.isMonthComplete ? PdfColors.green800 : PdfColors.orange800,
                          ),
                        ),
                        pw.Text(
                          r.isMonthComplete ? labels.complete : labels.monthNotComplete,
                          style: pw.TextStyle(
                            fontSize: 7,
                            color: r.isMonthComplete ? PdfColors.green700 : PdfColors.orange700,
                          ),
                        ),
                      ],
                    ),
                  ),
              ],
            ),
          ),
          pw.SizedBox(height: 14),

          // Meter details table
          _meterTable(r, b, s, labels),
          pw.SizedBox(height: 12),

          // Summary breakdown
          pw.Container(
            padding: const pw.EdgeInsets.all(10),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey50,
              borderRadius: pw.BorderRadius.circular(4),
              border: pw.Border.all(color: PdfColors.grey200),
            ),
            child: pw.Column(
              children: [
                _summaryRow(
                  labels.subtotalElec,
                  '${formatKwh(b.elecUsageKwh)}  →  ${formatKhr(b.elecAmountKhr)}',
                  false,
                ),
                pw.SizedBox(height: 4),
                _summaryRow(
                  labels.subtotalWater,
                  '${formatM3(b.waterUsageM3)}  →  ${formatKhr(b.waterAmountKhr)}',
                  false,
                ),
                pw.Divider(color: PdfColors.grey300, height: 12),
                _summaryRow(
                  labels.total,
                  formatKhr(b.totalKhr),
                  true,
                ),
                pw.SizedBox(height: 2),
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.end,
                  children: [
                    pw.Text(
                      formatUsd(b.totalUsd),
                      style: const pw.TextStyle(
                        fontSize: 10,
                        color: PdfColors.grey700,
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
          pw.Spacer(),
          pw.Center(
            child: pw.Text(
              labels.generatedBy,
              style: const pw.TextStyle(
                fontSize: 9,
                color: PdfColors.grey600,
              ),
            ),
          ),
        ],
      ),
    );
  }

  pw.Widget _summaryRow(String label, String value, bool bold) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Text(
          label,
          style: pw.TextStyle(
            fontSize: bold ? 12 : 10,
            fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal,
          ),
        ),
        pw.Text(
          value,
          style: pw.TextStyle(
            fontSize: bold ? 14 : 10,
            fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal,
          ),
        ),
      ],
    );
  }

  pw.Widget _meterTable(Reading r, BillBreakdown b, AppSettings s, _InvoiceLabels labels) {
    pw.TableRow header() => pw.TableRow(
      decoration: const pw.BoxDecoration(color: PdfColors.grey200),
      children: [
        _cell(labels.item, bold: true),
        _cell(labels.prevMeter, bold: true, align: pw.TextAlign.right),
        _cell(labels.currMeter, bold: true, align: pw.TextAlign.right),
        _cell(labels.usage, bold: true, align: pw.TextAlign.right),
        _cell(labels.rate, bold: true, align: pw.TextAlign.right),
        _cell(labels.amount, bold: true, align: pw.TextAlign.right),
      ],
    );
    pw.TableRow row({
      required String label,
      required double prev,
      required double curr,
      required double usage,
      required String usageUnit,
      required double rate,
      required String rateUnit,
      required double amount,
    }) => pw.TableRow(
      children: [
        _cell(label),
        _cell(_num(prev), align: pw.TextAlign.right),
        _cell(_num(curr), align: pw.TextAlign.right),
        _cell('${_num(usage)} $usageUnit', align: pw.TextAlign.right),
        _cell('${formatInt(rate)} $rateUnit', align: pw.TextAlign.right),
        _cell(formatKhr(amount), align: pw.TextAlign.right),
      ],
    );

    return pw.Table(
      border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
      columnWidths: const {
        0: pw.FlexColumnWidth(2),
        1: pw.FlexColumnWidth(1.5),
        2: pw.FlexColumnWidth(1.5),
        3: pw.FlexColumnWidth(1.8),
        4: pw.FlexColumnWidth(1.6),
        5: pw.FlexColumnWidth(2),
      },
      children: [
        header(),
        row(
          label: labels.electricity,
          prev: r.prevElec,
          curr: r.currElec,
          usage: b.elecUsageKwh,
          usageUnit: labels.kwhUnit,
          rate: s.elecRateKhrPerKwh,
          rateUnit: labels.perKwh,
          amount: b.elecAmountKhr,
        ),
        row(
          label: labels.water,
          prev: r.prevWater,
          curr: r.currWater,
          usage: b.waterUsageM3,
          usageUnit: labels.m3Unit,
          rate: s.waterRateKhrPerM3,
          rateUnit: labels.perM3,
          amount: b.waterAmountKhr,
        ),
      ],
    );
  }

  String _num(double v) => v == v.roundToDouble()
      ? formatInt(v)
      : v.toStringAsFixed(1);

  pw.Widget _cell(
    String text, {
    bool bold = false,
    pw.TextAlign align = pw.TextAlign.left,
  }) => pw.Padding(
    padding: const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 6),
    child: pw.Text(
      text,
      textAlign: align,
      style: pw.TextStyle(
        fontSize: 9,
        fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal,
      ),
    ),
  );

  Future<void> printDoc(pw.Document doc, {String? name}) async {
    await Printing.layoutPdf(
      onLayout: (format) => doc.save(),
      name: name ?? 'invoice',
    );
  }

  Future<void> shareDoc(pw.Document doc, {required String fileName}) async {
    final bytes = await doc.save();
    await Printing.sharePdf(bytes: bytes, filename: fileName);
  }
}
