// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDozzyQ3_v9_fYyCjmzUkiDGHW4m5M7O58',
    appId: '1:927901165362:web:5fed331352e1f4fa19192b',
    messagingSenderId: '927901165362',
    projectId: 'my-bill-1a987',
    authDomain: 'my-bill-1a987.firebaseapp.com',
    storageBucket: 'my-bill-1a987.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIJqU5YgfagzifW9j3rbHJ4I0NvdNWlRc',
    appId: '1:927901165362:android:e8fcbf8cb923316819192b',
    messagingSenderId: '927901165362',
    projectId: 'my-bill-1a987',
    storageBucket: 'my-bill-1a987.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-caDB9WgRG-O2VJnrB9K4miUIfBc4wpQ',
    appId: '1:927901165362:ios:7256c5610424c36219192b',
    messagingSenderId: '927901165362',
    projectId: 'my-bill-1a987',
    storageBucket: 'my-bill-1a987.firebasestorage.app',
    iosBundleId: 'com.example.myBill',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-caDB9WgRG-O2VJnrB9K4miUIfBc4wpQ',
    appId: '1:927901165362:ios:7256c5610424c36219192b',
    messagingSenderId: '927901165362',
    projectId: 'my-bill-1a987',
    storageBucket: 'my-bill-1a987.firebasestorage.app',
    iosBundleId: 'com.example.myBill',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDozzyQ3_v9_fYyCjmzUkiDGHW4m5M7O58',
    appId: '1:927901165362:web:f00724ced7bc7cc519192b',
    messagingSenderId: '927901165362',
    projectId: 'my-bill-1a987',
    authDomain: 'my-bill-1a987.firebaseapp.com',
    storageBucket: 'my-bill-1a987.firebasestorage.app',
  );
}
